name: CI

on:
  push:
    branches:
      - main
      - '[0-9].[0-9]+'  # matches to backport branches, e.g. 3.6
    tags: [ 'v*' ]
  pull_request:
    branches:
      - main
      - '[0-9].[0-9]+'
      - 'update/pre-commit-autoupdate'

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Run pre-commit
      uses: pre-commit/action@v2.0.3

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        with-groups: [with_groups, without_groups]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: testorm
          POSTGRES_PASSWORD: testorm
          POSTGRES_DB: testorm
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        cache: pip
        cache-dependency-path: |
          requirements/base.txt
          requirements/local.txt
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/local.txt
    - name: Test
      run: |
        python main.py ${{ matrix.with-groups }}
